cartesian_limits:
  max_trans_vel: 1.0   # max translational velocity in 
  max_trans_acc: 2.25  # max translational acceleration 
  max_trans_dec: -5    # max translational deceleration
  max_rot_vel: 1.57    # max rotational velocity 
  